<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>inspire_hand_eth</name>
  <version>1.0.0</version>
  <description>Inspire Hand Modbus TCP control package for ROS 2 (C++ only)</description>

  <maintainer email="inspire001@todo.todo">inspire001</maintainer>
  <license>MIT</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Build dependencies -->
  <build_depend>rclcpp</build_depend>
  <build_depend>service_interfaces</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>ament_index_cpp</build_depend>

  <!-- Exec dependencies -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>service_interfaces</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>ament_index_cpp</exec_depend>

  <!-- Test dependencies -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
