<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>roas2_bringup</name>
  <version>0.0.0</version>
  <description>ROAS2 integrated bringup package</description>
  <maintainer email="support@roas.co.kr">roas</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>xacro</depend>
  <depend>robot_state_publisher</depend>
  
  <!-- Package dependencies for integrated launch -->
  <exec_depend>slamware_ros_sdk</exec_depend>
  <exec_depend>slamtec_description</exec_depend>
  <exec_depend>robotiq_gripper_controller</exec_depend>
  <exec_depend>microstrain_inertial_driver</exec_depend>
  <exec_depend>kortex_bringup</exec_depend>
  <exec_depend>kortex_description</exec_depend>
  <exec_depend>kinova_gen3_moveit_config</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
